import img from '../images/sample.jpg';
import img2 from '../images/sample2.jpg';
import img3 from '../images/sample3.jpg';

const films = [
  {
    link: img,
    name: 'какое-то кино',
    time: 11,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 22,
    id: 1234567,
    saved: true,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 33,
    id: 1234567,
    saved: false,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 44,
    id: 1234567,
    saved: true,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 55,
    id: 1234567,
    saved: false,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 66,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 77,
    id: 1234567,
    saved: false,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 88,
    id: 1234567,
    saved: true,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 22,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 33,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 44,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 55,
    id: 1234567,
    saved: false,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 66,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 77,
    id: 1234567,
    saved: false,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 88,
    id: 1234567,
    saved: true,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 22,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 33,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 44,
    id: 1234567,
    saved: true,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 55,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 66,
    id: 1234567,
    saved: false,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 77,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 88,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 22,
    id: 1234567,
    saved: true,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 33,
    id: 1234567,
    saved: false,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 44,
    id: 1234567,
    saved: true,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 55,
    id: 1234567,
    saved: false,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 66,
    id: 1234567,
    saved: false,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 77,
    id: 1234567,
    saved: false,
  },
  {
    link: img3,
    name: 'какое-то кино',
    time: 88,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 99,
    id: 1234567,
    saved: false,
  },
];

const savedFilms = [
  {
    link: img3,
    name: 'какое-то кино',
    time: 88,
    id: 1234567,
    saved: true,
  },
  {
    link: img,
    name: 'какое-то кино',
    time: 22,
    id: 1234567,
    saved: true,
  },
  {
    link: img2,
    name: 'какое-то кино',
    time: 66,
    id: 1234567,
    saved: false,
  },
];

export { films, savedFilms };
